---
name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Trigger every day at 16:00 UTC
    - cron:  '0 16 * * *'
  workflow_dispatch:

jobs:
  golangci-pr:
    if: github.ref != 'refs/heads/main'
    name: lint-pr-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          only-new-issues: true
  golangci-main:
    if: github.ref == 'refs/heads/main'
    name: lint-main-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          only-new-issues: true
          args: --issues-exit-code=0
  build:
    needs: [golangci-pr, golangci-main]
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    name: build
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go Fmt
        run: go fmt ./...

      - name: Build
        run: go build -v ./...
